CREATE DATABASE ZEPTO_ANALYSIS;
USE ZEPTO_ANALYSIS;

RENAME TABLE ZEPTO_V2 TO ZEPTO_DATA;

SET SQL_SAFE_UPDATES = 0;

SELECT * FROM ZEPTO_DATA;

-- SELECT NAME,count(*) FROM ZEPTO_DATA GROUP BY NAME;

# DATA EXPLORATION

-- COUNT OF ROWS
SELECT COUNT(*) FROM ZEPTO_DATA;

-- SAMPLE DATA
SELECT *FROM ZEPTO_DATA LIMIT 10;

-- NULL VALUES
SELECT *FROM ZEPTO_DATA
WHERE NAME IS NULL
OR
CATEGORY IS NULL
OR
MRP IS NULL
OR
DISCOUNTPERCENT IS NULL
OR 
DISCOUNTEDSELLINGPRICE IS NULL
OR 
WEIGHTINGMS IS NULL
OR
OUTOFSTOCK IS NULL
OR 
QUANTITY;

-- DIFFERENT PRODUCT CATEGORIES
SELECT DISTINCT CATEGORY
FROM ZEPTO_DATA 
ORDER BY CATEGORY;

# DATA CLEANING

-- PRODUCTS WITH PRICE = 0
SELECT *FROM ZEPTO_DATA
WHERE MRP = 0;

DELETE FROM ZEPTO_DATA
WHERE MRP = 0;

-- CONVERT PAISE TO RUPEES
UPDATE ZEPTO_DATA
SET MRP = MRP/100.0,
DISCOUNTEDSELLINGPRICE = DISCOUNTEDSELLINGPRICE/100.0;

# BUSINESS INSIGHTS

-- FIND THE TOP 10 BEST-VALUE PRODUCTS BASED ON THE DISCOUNT PERCENTAGE
SELECT * FROM ZEPTO_DATA
ORDER BY DISCOUNTPERCENT DESC LIMIT 10;

-- WHAT ARE THE PRODUCTS WITH HIGH MRP BUT OUT OF STOCK
SELECT *
FROM Zepto_Data
WHERE outOfStock = 'TRUE'
ORDER BY mrp DESC;

-- CALCULATE ESTIMATED REVENUE FOR EACH CATEGORY
SELECT CATEGORY,SUM(AVAILABLEQUANTITY*DISCOUNTEDSELLINGPRICE)AS CAT_REVENUE
FROM ZEPTO_DATA
GROUP BY CATEGORY
ORDER BY CAT_REVENUE DESC;

-- FIND ALL PRODUCTS WHERE MRP IS GREATER THAN 500 AND DISCOUNT IS LESS THAN 10%
SELECT *FROM ZEPTO_DATA
WHERE MRP > 500 AND DISCOUNTPERCENT <10;

-- IDENTIFY THE TOP 5 CATEGORIES OFFERING THE HIGHEST AVERAGE DISCOUNT %
SELECT CATEGORY, AVG(DISCOUNTPERCENT) AS AVG_DISCOUNT 
FROM ZEPTO_DATA
GROUP BY CATEGORY
ORDER BY AVG_DISCOUNT DESC 
LIMIT 5;

-- FIND THE PRICE PER GRAM FOR PRODUCTS ABOVE 100G AND SORT BY BEST VALUE.
SELECT NAME,DISCOUNTEDSELLINGPRICE,WEIGHTINGMS,
ROUND(DISCOUNTEDSELLINGPRICE/WEIGHTINGMS,2)AS PER_GRAM
FROM ZEPTO_DATA 
WHERE WEIGHTINGMS>=100
ORDER BY PER_GRAM DESC;


-- GROUP THE PRODUCTS INTO CATEGORIES LIKE LOW , MEDIUM,BULK
SELECT NAME,WEIGHTINGMS,
	CASE WHEN WEIGHTINGMS<1000 THEN 'LOW'
         WHEN WEIGHTINGMS<5000 THEN 'MEDIUM'
         ELSE 'BULK'
         END AS WEIGHT_CATEGORY
FROM ZEPTO_DATA;

-- WHAT IS THE TOTAL INVENTORY WEIGHT PER CATEGORY
SELECT CATEGORY,
SUM(WEIGHTINGMS*AVAILABLEQUANTITY) AS TOTAL_WEIGHT
FROM ZEPTO_DATA
GROUP BY CATEGORY
ORDER BY TOTAL_WEIGHT DESC;



SELECT *FROM ZEPTO_DATA;
